{% set name = "geopandas" %}
{% set version = "1.0.1" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  # switch to GH archive rather than GH releases/download, to have the data files
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: c4c5467cdeb9080114cc70292e3c4d50f981eff156bcb7ac2b3e544d6897268a

build:
  number: 0
  skip: True  # [py<39 or s390x]

outputs:
  - name: {{ name }}-base
    script: build_base.sh   # [unix]
    script: build_base.bat  # [win]
    requirements:
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
        - packaging
        - pandas >=1.4.0
        - shapely >=2.0.0
        - numpy >=1.22
        - pyogrio >=0.7.2
        - pyproj >=3.3.0
      run_constrained:
        # geodatabase access
        # https://github.com/geopandas/geopandas/blob/v1.0.1/environment-dev.yml#L35
        - psycopg2 >=2.8.0
        - psycopg-binary >=3.1.0
        - sqlalchemy >=1.3
        - matplotlib-base >=3.5.0
        # parquet
        - pyarrow >=8.0.0
    test:
      imports:
        - geopandas
        - geopandas.io
      files:
        - test_data
      source_files:
        - geopandas/tests
        - geopandas/conftest.py
        - geopandas/io/tests
        - geopandas/tools/tests
      requires:
        - pip
        - pytest
        - pytest-xdist
      commands:
        - pip check
        # check that pip gets the correct version 
        - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
        - pytest -n auto -vv geopandas/tests
        - pytest -n auto -vv geopandas/io/tests  # [not (linux and aarch64)]
        # Skip flaky test test_write_read_file on linux-aarch64
        - pytest -n auto -vv geopandas/io/tests -k "not test_write_read_file"  # [linux and aarch64]
        - pytest -n auto -vv geopandas/tools/tests

  - name: {{ name }}
    requirements:
      host:
        - python
        - pip
        - setuptools >=61.0.0
        - wheel
      run:
        - python
        - {{ pin_subpackage('geopandas-base', exact=True) }}
        # extras for: plotting
        - folium
        # https://github.com/geopandas/geopandas/blob/v1.0.1/doc/source/getting_started/install.rst#dependencies
        # in the next version it will be bumped to 2.5.0 and added to pyproject.toml
        - mapclassify >=2.4.0
        - matplotlib-base
        - xyzservices
    test:
      imports:
        - geopandas
        - geopandas.io
        - geopandas.tools
        - geopandas.datasets
      files:
        - test_data
      source_files:
        - geopandas/tests
        - geopandas/conftest.py
      requires:
        - pip
        - pytest
        - pytest-xdist
      commands:
        - pip check
        # check that pip gets the correct version 
        - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
        - pytest -n auto -vv geopandas/tests

about:
  home: https://geopandas.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Geographic pandas extensions
  description: |
    GeoPandas is an open source project to make working with geospatial data in python easier.
    GeoPandas extends the datatypes used by pandas to allow spatial operations on geometric types.
    Geometric operations are performed by shapely. Geopandas further depends on fiona for file access and
    descartes and matplotlib for plotting.
    The goal of GeoPandas is to make working with geospatial data in python easier.
    It combines the capabilities of pandas and shapely, providing geospatial operations in pandas
    and a high-level interface to multiple geometries to shapely.
    GeoPandas enables you to easily do operations in python that would otherwise require a spatial database such as PostGIS.
  dev_url: https://github.com/geopandas/geopandas
  doc_url: https://geopandas.org/en/stable/docs.html

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
    - jdmcbr
    - martinfleis
