{% set version = "0.9.0" %}

package:
  name: geopandas
  version: {{ version }}

source:
  url: https://github.com/geopandas/geopandas/releases/download/v{{ version }}/geopandas-{{ version }}.tar.gz
  sha256: 63972ab4dc44c4029f340600dcb83264eb8132dd22b104da0b654bef7f42630a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.6
    - pandas >=0.24
    - shapely >=1.6
    - fiona >=1.8
    - pyproj >=2.2.0
    - rtree

test:
  imports:
    - geopandas
    - geopandas.io
  files:
    - test_data

about:
  home: http://geopandas.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: 'LICENSE.txt'
  summary: 'Geographic pandas extensions'
  dev_url: https://github.com/geopandas/geopandas
  doc_url: https://geopandas.readthedocs.io/en/latest/docs.html

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
    - jdmcbr
