{% set version = "0.4.0" %}

package:
  name: geopandas
  version: {{ version }}

source:
  url: https://github.com/geopandas/geopandas/releases/download/v{{ version }}/geopandas-{{ version }}.tar.gz
  sha256: 9f5d24d23f33e6d3267a633025e4d9e050b3a1e86d41a96d3ccc5ad95afec3db

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pandas
    - pyproj
    - shapely
    - fiona
    - six
    - rtree
    - descartes
    - matplotlib
    - psycopg2
    - sqlalchemy
    - pysal

test:
  imports:
    - geopandas
    - geopandas.io
  files:
    - test_data

about:
  home: http://geopandas.org
  license: BSD 3-clause
  # We can drop this when there is a next release and
  # https://github.com/geopandas/geopandas/pull/795 is merged.
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'Geographic pandas extensions'

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
    - jdmcbr
