{% set name = "geopandas" %}
{% set version = "0.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0acdacddefa176525e4da6d9aeeece225da26055c4becdc6e97cf40fa97c27f4

build:
  number: 0
  # rtree, fiona are missing on s390x.
  skip: True  # [py<38 or s390x or py>=310]

outputs:
  - name: geopandas-base
    script: build_base.sh   # [unix]
    script: build_base.bat  # [win]
    requirements:
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
        - packaging
        - pandas >=1.0.5
        - pyproj >=2.6.1.post1
        - shapely >=1.7

    test:
      imports:
        - geopandas
        - geopandas.io
        - geopandas.tools
        - geopandas.datasets
      files:
        - test_data

  - name: geopandas
    requirements:
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
        - {{ pin_subpackage('geopandas-base', exact=True) }}
        - fiona >=1.8
        # folium package isn't available yet on the defaults channel.
        #- folium
        - mapclassify >=2.4.0
        - matplotlib-base
        - rtree
        - xyzservices

    test:
      imports:
        - geopandas
        - geopandas.io
        - geopandas.tools
        - geopandas.datasets
      files:
        - test_data
      requires:
        - pip
      commands:
        - pip check

about:
  home: https://geopandas.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Geographic pandas extensions
  description: |
    GeoPandas is an open source project to make working with geospatial data in python easier.
    GeoPandas extends the datatypes used by pandas to allow spatial operations on geometric types.
    Geometric operations are performed by shapely. Geopandas further depends on fiona for file access and
    descartes and matplotlib for plotting.
    The goal of GeoPandas is to make working with geospatial data in python easier. 
    It combines the capabilities of pandas and shapely, providing geospatial operations in pandas 
    and a high-level interface to multiple geometries to shapely. 
    GeoPandas enables you to easily do operations in python that would otherwise require a spatial database such as PostGIS.
  dev_url: https://github.com/geopandas/geopandas
  doc_url: https://geopandas.org/en/stable/docs.html

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
    - jdmcbr
