{% set version = "0.10.1" %}

package:
  name: geopandas
  version: {{ version }}

source:
  url: https://github.com/geopandas/geopandas/releases/download/v{{ version }}/geopandas-{{ version }}.tar.gz
  sha256: 6429ee4e0cc94f26aff12139445196ef83fe17cadbe816925508a1799f60a681

build:
  number: 0
  noarch: python

outputs:
  - name: geopandas-base
    script: build_base.sh
    build:
      noarch: python
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python >=3.7
        - pip
      run:
        - python >=3.7
        - pandas >=0.25
        - shapely
        - pyproj >=2.2.0

    test:
      imports:
        - geopandas
        - geopandas.io
      files:
        - test_data

  - name: geopandas
    requirements:
      host:
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage('geopandas-base', exact=True) }}
        - fiona
        - rtree
        - matplotlib-base
        - mapclassify >=2.4.0
        - folium
        - xyzservices

    test:
      imports:
        - geopandas
        - geopandas.io
      files:
        - test_data

about:
  home: http://geopandas.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Geographic pandas extensions

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
    - jdmcbr
