{% set version = "0.12.2" %}

package:
  name: geopandas
  version: {{ version }}

source:
  url: https://github.com/geopandas/geopandas/releases/download/v{{ version }}/geopandas-{{ version }}.tar.gz
  sha256: 0acdacddefa176525e4da6d9aeeece225da26055c4becdc6e97cf40fa97c27f4

build:
  number: 1
  noarch: python

outputs:
  - name: geopandas-base
    script: build_base.sh
    build:
      noarch: python
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - pandas >=0.24
        - shapely
        - pyproj >=2.2.0

    test:
      imports:
        - geopandas
        - geopandas.io
      files:
        - test_data

  - name: geopandas
    requirements:
      host:
        - python >=3.6
      run:
        - python >=3.6
        - {{ pin_subpackage('geopandas-base', exact=True) }}
        - fiona
        - rtree
        - matplotlib-base
        - mapclassify >=2.2.0

    test:
      imports:
        - geopandas
        - geopandas.io
      files:
        - test_data

about:
  home: http://geopandas.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Geographic pandas extensions

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
    - jdmcbr
