travis:
  secure:
    BINSTAR_TOKEN: lnXWhchOlk3NmdAGh+MetwvaNIAvOzoMgPFtBDIThIQK1ViJNlHhBVsKUJD6+Eup5RGY9wW74beOKYJxAO7ej/8cw29NfJsWF9kfHmUoB5nh/hotsk1tM/LUtYCFjik/XtWDZT9iAgULnWsEqLdi3putBmoZpRN3c41AQfH96GcVlbGfcIicqJhg88mzOj6NmsYfEosOeBqv1ejftHyw7GuLWXSmJsjMCQqQ9U9Y1BQmQuzTdINzPqS8KSH1PX8LLJiVwY1cBIeNYFloNv9j742BvV1cLn5miKX+xY8T2dMAJyhUuubCBqRkJnaHKpf2P79qqS18Zt48N3z7XiKMvsBWbFWRONr51GJJSoHuMW8X+E+sPObmQLYrkw0y28p5HHs5QmqK8XAJsRRjfyqY2tQvvjRbTr/Vj4NloqSY4XChm5cRc3kLKOhXVKWQJ0W8tS7/eMkp615OhuYSiIeMUYNFDSL7VVqnP6gcV7oB1JNi/RI8SKr3ufazBGE1Ulyix+PAT5Q2ddWeU2gwotFwCs1FlzR/9h4M38ZcNB2VfGQl/AvmDnkqxxayZtd0F8bMLmENYk8xJDEryLYPAMV1jeH4gBU4FXhf4WOFAkOGKE2DKZBoW8n3BZJ7ZvlP3xEDtZpR+s2tncXBHCLgKDqlJiwckT/5UpKkRZWWTEkZBFQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
